### ISSUE TITLE
Deployment to git pages

### ISSUE THREAD

**Issue by Festy1** [Festy1/MY-PORTFOLIO#6]
https://festy1.github.io/MY-PORTFOLIO/

**Comment by Gambit142** [comment]
Hi @Festy1 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Application deployed using GitHub pages
- Application functions properly on GitHub Pages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
